require 'rails'
require 'devise'
require 'haml'
require 'carrierwave'
require 'jquery-rails'
require 'jquery-ui-rails'
require 'jquery-timepicker-addon-rails'
require 'js-routes'
require 'mini_magick'
require 'ckeditor'
require 'sanitize'
require 'remotipart'
require 'will_paginate'

require 'coalla/cms/engine'
require 'coalla/cms/version'
require 'coalla/ext/mapper'

require 'coalla/uploaders/file_uploader'
require 'coalla/uploaders/image_uploader'
require 'coalla/uploaders/meta_image_uploader'

require 'coalla/builders/policy'
require 'coalla/builders/form_builder'
require 'coalla/builders/table_builder'
require 'coalla/builders/link_renderer'
require 'coalla/builders/admin_structure'